import { test, expect } from '@playwright/test';
import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'node:fs';
import { loadEnvFile } from 'node:process';
import { randomUUID } from 'node:crypto';
import { unzipSync, zipSync, strFromU8, strToU8 } from 'fflate';

// Explicit opt-in, localhost app, and a fixed development project allowlist.
// Cleanup uses only question UUIDs generated by this invocation, including on failure.
// A synthetic attempt belongs to the existing seeded development admin.
test('development replacement preserves identities, grading and attempts; rejects stale reviews', async ({ page, baseURL }) => {
  test.skip(process.env.E2E_IMPORT_REPLACE !== '1', 'Opt in to temporary development fixtures.');
  test.setTimeout(180_000);
  page.setDefaultTimeout(15_000);
  await page.context().clearCookies();
  loadEnvFile('.env.local');
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL!;
  expect(new URL(url).hostname).toBe('ikzhizgsawzjpuuznfid.supabase.co');
  expect(['localhost','127.0.0.1']).toContain(new URL(baseURL!).hostname);
  const db = createClient(url, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, {auth:{persistSession:false,autoRefreshToken:false}});
  const signedIn = await db.auth.signInWithPassword({email:'admin@test.studyworks',password:'devseed123'});
  expect(signedIn.error).toBeNull();
  const run = randomUUID();
  const ids = [randomUUID(),randomUUID(),randomUUID()];
  const sources = ['ac472881','3f5a3602','3008cfc3'];
  const root = 'content/import/pilot/';
  const snapshot = JSON.parse(readFileSync(root+'analysis/bank-comparison.json','utf8'));
  const fixtures = sources.map((source,i) => {
    const original = snapshot.rows.find((r: {source_id:string}) => r.source_id === source);
    return { ...original, ...(i===0 ? {stimulus_html:original.stem_html,stimulus_rendered:original.stem_rendered,stem_html:'<p>Review the equations above.</p>',stem_rendered:null,domain_name:'Algebra'} : {}), id:ids[i],display_code:`TEST-${run.slice(0,8)}-${i}`,source_id:`import-test-${run}-${source}`,source_external_id:null,source:'generated',pool:'opt_in',updated_at:new Date().toISOString(),
      options:Array.isArray(original.options) ? original.options.map((o: object,j:number)=>({...o,id:`stable-${i}-${j}`})) : original.options };
  });
  const archive = unzipSync(readFileSync(root+'Algebra 10 questions and answers.mmd.zip'));
  for (const name of Object.keys(archive)) if (name.endsWith('.mmd')) {
    let mmd = strFromU8(archive[name]);
    for (let i=0;i<sources.length;i++) mmd = mmd.replaceAll(sources[i],fixtures[i].source_id);
    archive[name] = strToU8(mmd);
  }
  try {
    const inserted = await db.from('questions_v2').insert(fixtures);
    expect(inserted.error).toBeNull();
    const attempt = await db.from('attempts').insert({user_id:signedIn.data.user!.id,question_id:ids[0],is_correct:true}).select().single();
    expect(attempt.error).toBeNull();
    const before = await db.from('questions_v2').select('*').in('id',ids);
    expect(before.error).toBeNull();

    await page.goto('/login');
    await page.getByLabel(/email/i).fill('admin@test.studyworks');
    await page.getByLabel('Password',{exact:true}).fill('devseed123');
    await page.getByRole('button',{name:/^log in$/i}).click();
    await page.waitForURL(u=>!u.pathname.includes('/login'));
    await page.goto('/admin/questions/import');
    await page.locator('input[name="export"]').setInputFiles({name:'development-pilot.zip',mimeType:'application/zip',buffer:Buffer.from(zipSync(archive))});
    await page.getByRole('button',{name:'Compare with question bank',exact:true}).click();
    await expect(page.getByText(/10 questions · 3 with possible duplicates/)).toBeVisible();

    // Review is read-only, and the explicit confirmation gates the apply button.
    for (let i=0;i<ids.length;i++) {
      await page.getByRole('button',{name:new RegExp(fixtures[i].source_id)}).click();
      await page.getByRole('button',{name:'Prefer imported',exact:true}).click();
      const apply = page.getByRole('button',{name:'Import this question',exact:true});
      await expect(apply).toBeDisabled();
      const unchanged = await db.from('questions_v2').select('*').eq('id',ids[i]).single();
      expect(unchanged.data).toEqual(before.data!.find(r=>r.id===ids[i]));
      await page.getByRole('checkbox',{name:/Reviewed and ready/}).check();
      if (i===0) {
        await expect(apply).toBeDisabled();
        await page.getByRole('checkbox',{name:/Imported prompt includes the stimulus/}).check();
        await expect(page.getByRole('checkbox',{name:/Reviewed and ready/})).not.toBeChecked();
        await page.getByRole('checkbox',{name:/Reviewed and ready/}).check();
      }
      await expect(apply).toBeEnabled();
      if (i===2) {
        // Concurrent edit after comparison must be retained when stale apply fails.
        const changed = await db.from('questions_v2').update({difficulty:1}).eq('id',ids[i]);
        expect(changed.error).toBeNull();
        await apply.click();
        await expect(page.getByRole('region',{name:'Question review'})).toContainText('This question changed or was already applied.');
        const stale = await db.from('questions_v2').select('*').eq('id',ids[i]).single();
        expect(stale.data!.stem_html).toBe(fixtures[i].stem_html);
        expect(stale.data!.difficulty).toBe(1);
        // Recompare and explicitly review the new state before applying the table.
        await page.locator('summary').filter({hasText:'1. Choose your files'}).click();
        await page.getByRole('button',{name:'Compare with question bank',exact:true}).click();
        await expect(page.getByRole('button',{name:'Compare with question bank',exact:true})).toBeEnabled();
        await expect(page.getByText(/10 questions · 3 with possible duplicates/)).toBeVisible();
        await page.getByRole('button',{name:new RegExp(fixtures[i].source_id)}).click();
        await page.getByRole('button',{name:'Prefer imported',exact:true}).click();
        await page.getByRole('checkbox',{name:/Reviewed and ready/}).check();
      }
      await apply.click();
      await expect(page.getByRole('region',{name:'Question review'})).toContainText('Presentation replaced. Answers and student history preserved.');
      await expect(apply).toHaveCount(0);
    }
    const after = await db.from('questions_v2').select('*').in('id',ids);
    expect(after.error).toBeNull(); expect(after.data).toHaveLength(3);
    const presentationFields = new Set(['stem_html','rationale_html','options','stem_rendered','rationale_rendered','options_rendered','rendered_source_hash','updated_at','updated_by']);
    for (let i=0;i<ids.length;i++) {
      const old = before.data!.find(r=>r.id===ids[i])!;
      const next = after.data!.find(r=>r.id===ids[i])!;
      for (const key of Object.keys(old)) if (!presentationFields.has(key) && !(i===0 && ['stimulus_html','stimulus_rendered'].includes(key))) expect(next[key],key).toEqual(i===2 && key==='difficulty' ? 1 : old[key]);
      if (i===0) { expect(next.stimulus_html).toBeNull(); expect(next.stimulus_rendered).toBeNull(); }
      expect(next.stem_html).not.toBe(old.stem_html);
      expect(next.stem_rendered).toBeTruthy();
      expect(next.updated_by).toBeTruthy();
      if(i===1) {
        expect(next.stem_html).toContain('data:image/');
        expect(next.options.map((o: {id:string})=>o.id)).toEqual(old.options.map((o: {id:string})=>o.id));
      }
      if(i===2) expect(next.stem_html).toContain('<table');
      const history = await db.from('question_content_history').select('*').eq('question_id',ids[i]);
      expect(history.error).toBeNull(); expect(history.data).toHaveLength(i===2 ? 2 : 1);
      expect(history.data!.some(h=>h.stem_html===old.stem_html)).toBe(true);
      if (i===0) expect(history.data!.some(h=>h.stimulus_html===old.stimulus_html)).toBe(true);
    }
    const attemptAfter = await db.from('attempts').select('*').eq('id',attempt.data!.id).single();
    expect(attemptAfter.data).toEqual(attempt.data);
    console.log('PASS: equation, graph/options and table applied; all non-presentation fields and practice attempt preserved; history recorded; stale review rejected.');
  } finally {
    const cleanupAttempts = await db.from('attempts').delete().in('question_id',ids);
    expect(cleanupAttempts.error).toBeNull();
    const cleanupQuestions = await db.from('questions_v2').delete().in('id',ids);
    expect(cleanupQuestions.error).toBeNull();
    const remaining = await db.from('questions_v2').select('id').in('id',ids);
    expect(remaining.data).toEqual([]);
    const attemptsRemaining = await db.from('attempts').select('id').in('question_id',ids);
    expect(attemptsRemaining.error).toBeNull(); expect(attemptsRemaining.data).toEqual([]);
    const historyRemaining = await db.from('question_content_history').select('id').in('question_id',ids);
    expect(historyRemaining.data).toEqual([]);
    console.log('CLEANUP: temporary questions, attempts, content history removed.');
  }
});
