// Hypothetical data for a "reasonably well-established tutoring firm"
// with 15 tutors and 100 students. Used by the /features/tutor-managers/demo/*
// routes to render the real Studyworks manager templates with fictional
// content so we can screenshot them for the sales slideshow without
// exposing real student names.
//
// Design constraints:
//   - 15 tutors, 100 students total, realistic uneven distribution (a
//     few power tutors, several active tutors, some in onboarding,
//     and 2-3 brand-new hires with no students yet).
//   - Stats in the ranges a well-run prep firm would actually see:
//     accuracy 65-90%, SAT scores 1240-1540, 5-15 students per roster.
//   - All names are clearly fictional and diverse; no real identities.
//   - Numbers tie out across views where possible (e.g. questionsDone
//     in domain mastery sums to the top-line questionsDone stat on
//     the training profile).
//
// Lives in /lib (not /app) so both the live admin dashboard (if ever
// wanted for local previewing) and the demo pages can import from one
// source of truth.

// ─── 15 tutors ─────────────────────────────────────────────────────
export const DEMO_TUTORS = [
  {
    id: 't01',
    first_name: 'Delphine',
    last_name: 'Ocampo',
    email: 'delphine.ocampo@studyworks.demo',
    student_count: 15,
    // Teacher Data table fields
    activeStudents7d: 13,
    engagementRate: 87,
    avgStudentAccuracy: 82,
    avgQuestionsPerWeek: 68,
    avgBestTestScore: 1420,
    studentsTested: 14,
    assignmentsCreated: 47,
    assignmentCompletionRate: 89,
    // Team page rollup fields
    rosterQuestionsDone: 5117,
    rosterAccuracy: 82,
    rosterAvgScore: 1420,
    rosterTestCount: 41,
  },
  {
    id: 't02',
    first_name: 'Aisha',
    last_name: 'Bello',
    email: 'aisha.bello@studyworks.demo',
    student_count: 14,
    activeStudents7d: 11,
    engagementRate: 79,
    avgStudentAccuracy: 78,
    avgQuestionsPerWeek: 55,
    avgBestTestScore: 1380,
    studentsTested: 12,
    assignmentsCreated: 38,
    assignmentCompletionRate: 85,
    rosterQuestionsDone: 3468,
    rosterAccuracy: 78,
    rosterAvgScore: 1380,
    rosterTestCount: 36,
  },
  {
    id: 't03',
    first_name: 'Felipe',
    last_name: 'Navarro',
    email: 'felipe.navarro@studyworks.demo',
    student_count: 12,
    activeStudents7d: 10,
    engagementRate: 83,
    avgStudentAccuracy: 75,
    avgQuestionsPerWeek: 62,
    avgBestTestScore: 1350,
    studentsTested: 11,
    assignmentsCreated: 42,
    assignmentCompletionRate: 81,
    rosterQuestionsDone: 2976,
    rosterAccuracy: 75,
    rosterAvgScore: 1350,
    rosterTestCount: 28,
  },
  {
    id: 't04',
    first_name: 'Priya',
    last_name: 'Ramanathan',
    email: 'priya.ramanathan@studyworks.demo',
    student_count: 10,
    activeStudents7d: 8,
    engagementRate: 80,
    avgStudentAccuracy: 76,
    avgQuestionsPerWeek: 49,
    avgBestTestScore: 1390,
    studentsTested: 9,
    assignmentsCreated: 31,
    assignmentCompletionRate: 88,
    rosterQuestionsDone: 2450,
    rosterAccuracy: 76,
    rosterAvgScore: 1390,
    rosterTestCount: 27,
  },
  {
    id: 't05',
    first_name: 'Nadir',
    last_name: 'Qureshi',
    email: 'nadir.qureshi@studyworks.demo',
    student_count: 9,
    activeStudents7d: 7,
    engagementRate: 78,
    avgStudentAccuracy: 73,
    avgQuestionsPerWeek: 44,
    avgBestTestScore: 1320,
    studentsTested: 8,
    assignmentsCreated: 28,
    assignmentCompletionRate: 79,
    rosterQuestionsDone: 1584,
    rosterAccuracy: 73,
    rosterAvgScore: 1320,
    rosterTestCount: 19,
  },
  {
    id: 't06',
    first_name: 'Hana',
    last_name: 'Takeda',
    email: 'hana.takeda@studyworks.demo',
    student_count: 8,
    activeStudents7d: 6,
    engagementRate: 75,
    avgStudentAccuracy: 80,
    avgQuestionsPerWeek: 52,
    avgBestTestScore: 1410,
    studentsTested: 8,
    assignmentsCreated: 25,
    assignmentCompletionRate: 84,
    rosterQuestionsDone: 2080,
    rosterAccuracy: 80,
    rosterAvgScore: 1410,
    rosterTestCount: 22,
  },
  {
    id: 't07',
    first_name: 'Isabel',
    last_name: 'Conti',
    email: 'isabel.conti@studyworks.demo',
    student_count: 7,
    activeStudents7d: 6,
    engagementRate: 86,
    avgStudentAccuracy: 77,
    avgQuestionsPerWeek: 45,
    avgBestTestScore: 1360,
    studentsTested: 7,
    assignmentsCreated: 21,
    assignmentCompletionRate: 90,
    rosterQuestionsDone: 1575,
    rosterAccuracy: 77,
    rosterAvgScore: 1360,
    rosterTestCount: 19,
  },
  {
    id: 't08',
    first_name: 'Marisol',
    last_name: 'Vance',
    email: 'marisol.vance@studyworks.demo',
    student_count: 7,
    activeStudents7d: 5,
    engagementRate: 71,
    avgStudentAccuracy: 72,
    avgQuestionsPerWeek: 38,
    avgBestTestScore: 1290,
    studentsTested: 6,
    assignmentsCreated: 22,
    assignmentCompletionRate: 73,
    rosterQuestionsDone: 1064,
    rosterAccuracy: 72,
    rosterAvgScore: 1290,
    rosterTestCount: 13,
  },
  {
    id: 't09',
    first_name: 'Cameron',
    last_name: 'Fitz',
    email: 'cameron.fitz@studyworks.demo',
    student_count: 6,
    activeStudents7d: 4,
    engagementRate: 67,
    avgStudentAccuracy: 69,
    avgQuestionsPerWeek: 32,
    avgBestTestScore: 1270,
    studentsTested: 5,
    assignmentsCreated: 18,
    assignmentCompletionRate: 67,
    rosterQuestionsDone: 768,
    rosterAccuracy: 69,
    rosterAvgScore: 1270,
    rosterTestCount: 10,
  },
  {
    id: 't10',
    first_name: 'Kirra',
    last_name: 'Nguyen',
    email: 'kirra.nguyen@studyworks.demo',
    student_count: 5,
    activeStudents7d: 4,
    engagementRate: 80,
    avgStudentAccuracy: 74,
    avgQuestionsPerWeek: 40,
    avgBestTestScore: 1340,
    studentsTested: 5,
    assignmentsCreated: 16,
    assignmentCompletionRate: 78,
    rosterQuestionsDone: 800,
    rosterAccuracy: 74,
    rosterAvgScore: 1340,
    rosterTestCount: 12,
  },
  {
    id: 't11',
    first_name: 'Lior',
    last_name: 'Shaked',
    email: 'lior.shaked@studyworks.demo',
    student_count: 4,
    activeStudents7d: 3,
    engagementRate: 75,
    avgStudentAccuracy: 71,
    avgQuestionsPerWeek: 36,
    avgBestTestScore: 1310,
    studentsTested: 4,
    assignmentsCreated: 12,
    assignmentCompletionRate: 74,
    rosterQuestionsDone: 504,
    rosterAccuracy: 71,
    rosterAvgScore: 1310,
    rosterTestCount: 8,
  },
  {
    id: 't12',
    first_name: 'Ezekiel',
    last_name: 'Grant',
    email: 'ezekiel.grant@studyworks.demo',
    student_count: 3,
    activeStudents7d: 2,
    engagementRate: 67,
    avgStudentAccuracy: 68,
    avgQuestionsPerWeek: 28,
    avgBestTestScore: 1240,
    studentsTested: 2,
    assignmentsCreated: 9,
    assignmentCompletionRate: 60,
    rosterQuestionsDone: 252,
    rosterAccuracy: 68,
    rosterAvgScore: 1240,
    rosterTestCount: 5,
  },
  // Three tutors still in onboarding / no assigned students yet.
  // The "new hire" bucket — realistic for a growing firm.
  {
    id: 't13',
    first_name: 'Jaxon',
    last_name: 'Reeves',
    email: 'jaxon.reeves@studyworks.demo',
    student_count: 0,
    activeStudents7d: 0,
    engagementRate: null,
    avgStudentAccuracy: null,
    avgQuestionsPerWeek: 0,
    avgBestTestScore: null,
    studentsTested: 0,
    assignmentsCreated: 0,
    assignmentCompletionRate: null,
    rosterQuestionsDone: 0,
    rosterAccuracy: null,
    rosterAvgScore: null,
    rosterTestCount: 0,
  },
  {
    id: 't14',
    first_name: 'Quinn',
    last_name: 'Bartos',
    email: 'quinn.bartos@studyworks.demo',
    student_count: 0,
    activeStudents7d: 0,
    engagementRate: null,
    avgStudentAccuracy: null,
    avgQuestionsPerWeek: 0,
    avgBestTestScore: null,
    studentsTested: 0,
    assignmentsCreated: 0,
    assignmentCompletionRate: null,
    rosterQuestionsDone: 0,
    rosterAccuracy: null,
    rosterAvgScore: null,
    rosterTestCount: 0,
  },
  {
    id: 't15',
    first_name: 'Rowan',
    last_name: 'McElroy',
    email: 'rowan.mcelroy@studyworks.demo',
    student_count: 0,
    activeStudents7d: 0,
    engagementRate: null,
    avgStudentAccuracy: null,
    avgQuestionsPerWeek: 0,
    avgBestTestScore: null,
    studentsTested: 0,
    assignmentsCreated: 0,
    assignmentCompletionRate: null,
    rosterQuestionsDone: 0,
    rosterAccuracy: null,
    rosterAvgScore: null,
    rosterTestCount: 0,
  },
];

// ─── Training profile for one showcase tutor ──────────────────────
// We pick Delphine Ocampo because her numbers are the strongest and
// the Training slide is the single most impressive screenshot in the
// deck. Domain numbers sum to the top-line questionsDone / accuracy.
export const DEMO_FEATURED_TUTOR = {
  id: 't01',
  first_name: 'Delphine',
  last_name: 'Ocampo',
  name: 'Delphine Ocampo',
  email: 'delphine.ocampo@studyworks.demo',
};

export const DEMO_FEATURED_TRAINING = {
  questionsDone: 387,
  questionsCorrect: 321,
  accuracy: 83,

  practiceTests: [
    {
      id: 'pt01',
      test_name: 'SAT Practice Test 4 (Adaptive)',
      finished_at: '2026-04-02T18:30:00Z',
      composite: 1540,
      rw_scaled: 770,
      math_scaled: 770,
    },
    {
      id: 'pt02',
      test_name: 'SAT Practice Test 2 (Adaptive)',
      finished_at: '2026-03-18T17:15:00Z',
      composite: 1480,
      rw_scaled: 740,
      math_scaled: 740,
    },
    {
      id: 'pt03',
      test_name: 'SAT Practice Test 1 (Adaptive)',
      finished_at: '2026-02-28T19:00:00Z',
      composite: 1420,
      rw_scaled: 710,
      math_scaled: 710,
    },
  ],

  recentSessions: [
    { date: '2026-04-09', total: 22, correct: 20 },
    { date: '2026-04-07', total: 15, correct: 13 },
    { date: '2026-04-06', total: 28, correct: 23 },
    { date: '2026-04-05', total: 18, correct: 16 },
    { date: '2026-04-03', total: 24, correct: 20 },
    { date: '2026-04-02', total: 31, correct: 27 },
    { date: '2026-03-30', total: 20, correct: 17 },
  ],

  // Reading and Writing domains (isEnglish = true)
  // Totals: 164/192 = 85%
  // Math domains (isEnglish = false)
  // Totals: 157/195 = 80.5%
  // Grand totals: 321/387 = 83% — ties out with top-line accuracy.
  domainMastery: [
    {
      domain_name: 'Information and Ideas',
      isEnglish: true,
      correct: 43,
      total: 50,
      accuracy: 86,
      skills: [
        { skill_name: 'Central Ideas and Details', correct: 14, total: 16, accuracy: 88 },
        { skill_name: 'Inferences', correct: 12, total: 14, accuracy: 86 },
        { skill_name: 'Command of Evidence (Textual)', correct: 10, total: 12, accuracy: 83 },
        { skill_name: 'Command of Evidence (Quantitative)', correct: 7, total: 8, accuracy: 88 },
      ],
    },
    {
      domain_name: 'Craft and Structure',
      isEnglish: true,
      correct: 38,
      total: 45,
      accuracy: 84,
      skills: [
        { skill_name: 'Words in Context', correct: 13, total: 15, accuracy: 87 },
        { skill_name: 'Text Structure and Purpose', correct: 12, total: 14, accuracy: 86 },
        { skill_name: 'Cross-Text Connections', correct: 13, total: 16, accuracy: 81 },
      ],
    },
    {
      domain_name: 'Expression of Ideas',
      isEnglish: true,
      correct: 35,
      total: 42,
      accuracy: 83,
      skills: [
        { skill_name: 'Rhetorical Synthesis', correct: 18, total: 22, accuracy: 82 },
        { skill_name: 'Transitions', correct: 17, total: 20, accuracy: 85 },
      ],
    },
    {
      domain_name: 'Standard English Conventions',
      isEnglish: true,
      correct: 48,
      total: 55,
      accuracy: 87,
      skills: [
        { skill_name: 'Boundaries', correct: 18, total: 20, accuracy: 90 },
        { skill_name: 'Form, Structure, and Sense', correct: 30, total: 35, accuracy: 86 },
      ],
    },
    {
      domain_name: 'Algebra',
      isEnglish: false,
      correct: 52,
      total: 60,
      accuracy: 87,
      skills: [
        { skill_name: 'Linear Equations (one variable)', correct: 14, total: 15, accuracy: 93 },
        { skill_name: 'Linear Equations (two variables)', correct: 13, total: 15, accuracy: 87 },
        { skill_name: 'Linear Functions', correct: 12, total: 15, accuracy: 80 },
        { skill_name: 'Systems of Linear Equations', correct: 13, total: 15, accuracy: 87 },
      ],
    },
    {
      domain_name: 'Advanced Math',
      isEnglish: false,
      correct: 41,
      total: 52,
      accuracy: 79,
      skills: [
        { skill_name: 'Nonlinear Equations', correct: 13, total: 16, accuracy: 81 },
        { skill_name: 'Nonlinear Functions', correct: 14, total: 18, accuracy: 78 },
        { skill_name: 'Equivalent Expressions', correct: 14, total: 18, accuracy: 78 },
      ],
    },
    {
      domain_name: 'Problem-Solving and Data Analysis',
      isEnglish: false,
      correct: 36,
      total: 45,
      accuracy: 80,
      skills: [
        { skill_name: 'Ratios, Rates, Proportions', correct: 12, total: 15, accuracy: 80 },
        { skill_name: 'Percentages', correct: 11, total: 13, accuracy: 85 },
        { skill_name: 'Data Inferences', correct: 13, total: 17, accuracy: 76 },
      ],
    },
    {
      domain_name: 'Geometry and Trigonometry',
      isEnglish: false,
      correct: 28,
      total: 38,
      accuracy: 74,
      skills: [
        { skill_name: 'Area and Volume', correct: 10, total: 13, accuracy: 77 },
        { skill_name: 'Lines, Angles, Triangles', correct: 11, total: 14, accuracy: 79 },
        { skill_name: 'Right Triangles and Trigonometry', correct: 7, total: 11, accuracy: 64 },
      ],
    },
  ],
};

// Convenience: total student count sanity check.
// 15+14+12+10+9+8+7+7+6+5+4+3+0+0+0 = 100 ✓
export const DEMO_TOTAL_STUDENTS = DEMO_TUTORS.reduce(
  (s, t) => s + t.student_count,
  0
);
