import type { Metadata } from 'next';

// Canonical site identity — the single source of truth for the
// origin, the public-facing name, and the default title/description
// used by the metadata routes (app/robots.ts, app/sitemap.ts) and
// every public page's `metadata` export.
//
// Why a fixed canonical origin rather than reading the request host:
// the same production deployment answers on four hosts —
// studyworks.io, www.studyworks.io, app.studyworksprep.com, and the
// sat-practice-app-*.vercel.app aliases — with byte-identical HTML
// and no redirect between them. Left alone that is four copies of
// every page as far as a crawler is concerned, and the one a search
// engine or a school's content filter happens to sample is arbitrary.
// Pinning the origin here means every host emits a canonical/og:url
// pointing at studyworks.io, so the duplicates collapse onto one
// identity no matter which door a crawler comes through.
//
// Deliberately a constant, and deliberately NOT NEXT_PUBLIC_SITE_URL.
// The two look interchangeable and are not:
//
//   NEXT_PUBLIC_SITE_URL is functional — "where do I send this user
//   back to" for Stripe redirects and emailed links. It has to match
//   a host that actually works for the caller, and it is
//   http://localhost:3000 in local dev.
//
//   This is an identity — the one URL every copy of a page agrees to
//   name as the original. Its whole job is to be identical on all
//   four hosts and in every deployment. Wiring it to the functional
//   variable would mean a local build emitting canonical
//   http://localhost:3000, and a production env var edit silently
//   re-pointing canonicalization at a different host.
//
// Preview deployments canonicalize to production, which is what you
// want: it folds them into the real page rather than competing with
// it. Change this only to move the site's public identity.
export const siteUrl = 'https://studyworks.io';

export const siteName = 'Studyworks';

// Read by a human first and a classifier second. The previous value
// ("Practice SAT questions with Supabase + Next.js") described the
// stack, not the product — a school web filter or a link preview had
// nothing to go on that said "test prep for students". Name the
// audience (high school students), the tests (SAT, ACT), and the
// thing it actually is (practice + lessons), in that order.
export const siteTitle = 'Studyworks — SAT & ACT Practice for Students';

export const siteDescription =
  'Adaptive SAT and ACT practice for high school students — real practice ' +
  'questions, full-length practice tests, score reports, and guided lessons.';

/** Absolute URL for a site-relative path. `absoluteUrl('/')` → origin + '/'. */
export function absoluteUrl(path: string): string {
  return `${siteUrl}${path.startsWith('/') ? path : `/${path}`}`;
}

// The card generated by app/opengraph-image.tsx, described explicitly.
//
// Next attaches a file-convention OG image to the segment that
// declares it, but metadata merging replaces the whole `openGraph`
// object when a child declares one — so any page setting its own
// og:title silently drops the inherited og:image. Restating the image
// on every page that overrides openGraph is what keeps link previews
// working outside the homepage. The URL is relative and resolves
// against metadataBase (set in app/layout.js).
const ogImage = {
  url: '/opengraph-image',
  width: 1200,
  height: 630,
  alt: 'Studyworks — SAT & ACT practice for high school students',
  type: 'image/png',
};

/**
 * Per-page metadata for a public, indexable page.
 *
 * Canonical and og:url have to be set per route, not once in the root
 * layout: a layout-level value is inherited verbatim by every child,
 * which would tell crawlers that /features/teachers and /subscribe are
 * both really the homepage. `path` is the canonical path for THIS page
 * — pass the path of another page to fold a duplicate into it (see
 * app/login/page.js, which renders the same surface as `/`).
 */
export function publicPageMetadata({
  path,
  title,
  description,
}: {
  path: string;
  title: string;
  description: string;
}): Metadata {
  const url = absoluteUrl(path);
  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: {
      type: 'website',
      siteName,
      locale: 'en_US',
      url,
      title,
      description,
      images: [ogImage],
    },
    twitter: { card: 'summary_large_image', title, description, images: [ogImage] },
  };
}
